#### Vamos criar nossa primeira aplicação usando Pytorch! Aqui nós aprenderemos o que são Tensors e veremos algumas operações entre eles.

In [1]:
import torch

#### Para começar, criaremos 2 Tensors. Um Tensor pode ser interpretado basicamente como um array. A diferença é que ao criar esse array como um Tensor, ele pode ser executado em uma GPU.

#### É válido notar que a multiplicação de dois Tensors é element-wise.

In [3]:
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x*y)

tensor([10.,  3.])


#### Como estamos percebendo, os Tensors basicamente vão ser arrays como os da numpy. Desse modo, várias funções da numpy foram também copiadas para o torch. Veja os exemplo abaixo:

In [6]:
x = torch.zeros([2, 5])

print("x: ", x)
print("Shape de x: ", x.shape)

x:  tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape de x:  torch.Size([2, 5])


In [8]:
y = torch.rand([2, 5])
print("Shape: ", y.shape)
print(y)

Shape:  torch.Size([2, 5])
tensor([[0.3916, 0.6033, 0.4140, 0.7545, 0.6000],
        [0.3935, 0.0948, 0.5940, 0.8535, 0.7199]])


#### Reshape: No Numpy ou no Tensorflow temos um método chamado Reshape. No Torch, esse método é chamado de view.

#### No exemplo abaixo, pegamos o array y de dimensão [2, 5] e o transformamos em [1, 10].

In [14]:
y = y.view([1, 10])
print("Shape: ", y.shape)
print(y)

Shape:  torch.Size([1, 10])
tensor([[0.3916, 0.6033, 0.4140, 0.7545, 0.6000, 0.3935, 0.0948, 0.5940, 0.8535,
         0.7199]])
